
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Hana
 */
public class Frame1 extends javax.swing.JFrame {

    
    double ti, bt, h1; 
    String temp = "";

    /**
     * Creates new form Frame1
     */
    public Frame1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        berat = new javax.swing.JTextField();
        saran = new javax.swing.JTextField();
        tinggi = new javax.swing.JTextField();
        p = new javax.swing.JRadioButton();
        l = new javax.swing.JRadioButton();
        keluar = new javax.swing.JButton();
        hitung = new javax.swing.JButton();
        coba = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        ideal = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        nama = new javax.swing.JTextField();
        diagnosa = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setText("Berat Badan Ideal");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(180, 20, 150, 14);

        jLabel3.setText("Nama");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(80, 70, 50, 14);

        jLabel4.setText("Tinggi");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(80, 110, 50, 14);

        jLabel5.setText("cm");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(220, 110, 80, 14);

        jLabel6.setText("Diagnosa Kesehatan");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(160, 310, 210, 14);
        getContentPane().add(berat);
        berat.setBounds(160, 150, 50, 30);

        saran.setEditable(false);
        getContentPane().add(saran);
        saran.setBounds(70, 370, 330, 50);
        getContentPane().add(tinggi);
        tinggi.setBounds(160, 110, 50, 30);

        buttonGroup1.add(p);
        p.setText("Perempuan");
        getContentPane().add(p);
        p.setBounds(160, 200, 120, 23);

        buttonGroup1.add(l);
        l.setText("Laki Laki");
        getContentPane().add(l);
        l.setBounds(300, 200, 110, 23);

        keluar.setText("Keluar");
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });
        getContentPane().add(keluar);
        keluar.setBounds(280, 240, 80, 23);

        hitung.setText("Hitung");
        hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitungActionPerformed(evt);
            }
        });
        getContentPane().add(hitung);
        hitung.setBounds(80, 240, 80, 23);

        coba.setText("Coba Lagi");
        coba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cobaActionPerformed(evt);
            }
        });
        getContentPane().add(coba);
        coba.setBounds(180, 240, 90, 23);

        jLabel7.setText("Berat Badan");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(80, 150, 80, 14);

        jLabel8.setText("kg");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(300, 280, 80, 14);

        jLabel9.setText("Jenis Kelamin");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(80, 200, 80, 14);

        ideal.setEditable(false);
        getContentPane().add(ideal);
        ideal.setBounds(240, 270, 50, 30);

        jLabel10.setText("kg");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(220, 150, 80, 14);

        jLabel11.setText("Berat Badan Ideal anda adalah");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(60, 280, 230, 14);
        getContentPane().add(nama);
        nama.setBounds(160, 70, 190, 30);

        diagnosa.setEditable(false);
        getContentPane().add(diagnosa);
        diagnosa.setBounds(70, 330, 330, 30);

        setBounds(0, 0, 498, 477);
    }// </editor-fold>//GEN-END:initComponents

    private void hitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitungActionPerformed
        // TODO add your handling code here:
        
        if (nama.getText().equals("")|| tinggi.getText().equals("") || berat.getText().equals(""))
                    JOptionPane.showMessageDialog(null, "Data Harus diisikan semua");
        else if(p.isSelected() || l.isSelected())
        {
                try{
                    Proses();
                }
                catch(Exception e)
                {
                    JOptionPane.showMessageDialog(null,"Data  ada yang belum diisi");
                }
        }else{
        JOptionPane.showMessageDialog(null, "Isikan Jenis Kelamin");
        }
    }//GEN-LAST:event_hitungActionPerformed

    private void cobaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cobaActionPerformed
        // TODO add your handling code here:
        
        nama.setText("");
        tinggi.setText("");
        berat.setText("");
        ideal.setText("");
        diagnosa.setText("");
        saran.setText("");
        buttonGroup1.clearSelection();
        
    }//GEN-LAST:event_cobaActionPerformed

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_keluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField berat;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton coba;
    private javax.swing.JTextField diagnosa;
    private javax.swing.JButton hitung;
    private javax.swing.JTextField ideal;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton keluar;
    private javax.swing.JRadioButton l;
    private javax.swing.JTextField nama;
    private javax.swing.JRadioButton p;
    private javax.swing.JTextField saran;
    private javax.swing.JTextField tinggi;
    // End of variables declaration//GEN-END:variables

    private void Proses() {
        ti = Double.parseDouble(tinggi.getText());
        bt = Double.parseDouble(berat.getText());
        
        if(p.isSelected())
        {
            h1 = (ti - 100) * 1;
        }
        else if(l.isSelected())
        {
            h1 = (ti - 104) * 1;
        }
        
        temp = h1 +"";
        
        if(h1 < bt){
            ideal.setText(temp);
            diagnosa.setText("Maaf " + nama.getText() + " Sepertinya anda overweight");
            saran.setText("Banyak olahraga dan makan makanan sehat");}
        else if(h1 > bt){
            ideal.setText(temp);
            diagnosa.setText("Maaf " + nama.getText() + " Sepertinya anda Underweight");
            saran.setText("Banyak konsumsi makanan karbohidrat");}
        else{
            ideal.setText(temp);
            diagnosa.setText("Halo , " + nama.getText() + " Berat Badan anda ideal");
            saran.setText("Lanjutkan kebiasaan hidup sehat");
            }
        }
    }
        
        
            
